#================================
# Stages
#================================

stages:
    - build
    - deploy

#================================
# Before script
#================================    



#================================
# Build
#================================

build_dev:
    stage: build
    except:
        - master
    script:
        - 'C:\Tools\nuget.exe restore 3wBetManager-API.sln'
        - '"C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\MSBuild.exe" 3wBetManager-API.sln /p:Configuration=Release'
    artifacts:
        paths:
            - 3wBetManager-API/

build_prod:
    stage: build
    only:
        - master
    script:
        - 'C:\Tools\nuget.exe restore 3wBetManager-API.sln'
        - '"C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\MSBuild.exe" 3wBetManager-API.sln /p:Configuration=Release'
    artifacts:
        paths:
            - 3wBetManager-API/

#================================
# Deploy
#================================

deploy_dev:
    stage: deploy
    except:
        - master
    script:
        - 'call deploy.bat'
    after_script:
        - 'ECHO After Script'
        - 'exit 0'
    dependencies:
        - build_dev

deploy_prod:
    stage: deploy
    only:
        - master
    script:
        - 'powershell.exe Stop-Process -Name "3wBetManager-API" -ErrorAction silentlycontinue'
        - 'start 3wBetManager-API\bin\Release\3wBetManager-API.exe'
    dependencies:
        - build_prod
