#================================
# Stages
#================================

stages:
    - build
    - deploy
#    - integration

#================================
# Build
#================================

build:
    stage: build
    only:
        - master
    script:
        - 'C:\Tools\nuget.exe restore 3wBetManager-API.sln'
        - '"C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\MSBuild.exe" 3wBetManager-API.sln /p:Configuration=Release'
    before_script:
        - C:\Tools\BismiAppRunner\BismiAppRunner.exe STOP 3wBetManager-API
        - rmdir /s "C:\GitLab-Runner\builds\Sns1WAaE\0\RomanLeichnig\backend-bet-manager-group2"
    artifacts:
        paths:
            - 3wBetManager-API/
            - Command/
            - Test/

#================================
# Test
#================================


#================================
# Deploy
#================================

deploy:
    stage: deploy
    script:
        - 'ECHO Start Deploy'
        - 'C:\Tools\BismiAppRunner\BismiAppRunner.exe STOP 3wBetManager-API'
        - 'C:\Tools\BismiAppRunner\BismiAppRunner.exe START C:\GitLab-Runner\builds\Sns1WAaE\0\RomanLeichnig\backend-bet-manager-group2\3wBetManager-API\bin\Release\\ 3wBetManager-API.exe'
        - 'ECHO End Deploy'
        - 'exit 0'
    dependencies:
        - build


#================================
# Integration Test
#================================

#integration:
#    stage: integration
#    script:
#        - '"C:\Users\Administrator\AppData\Roaming\npm\newman.cmd" run postman\3wbetManager.postman_collection.json -e postman\PROD.postman_environment.json'
#    dependencies:
#        - deploy
