#================================
# Stages
#================================

stages:
    - build
    - deploy

#================================
# Before script
#================================    



#================================
# Build
#================================

build:
    stage: build
    only:
        - master
    script:
        - 'C:\Tools\nuget.exe restore 3wBetManager-API.sln'
        - '"C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\MSBuild.exe" 3wBetManager-API.sln /p:Configuration=Release'
    before_script:
        - C:\Tools\BismiAppRunner\BismiAppRunner.exe STOP 3wBetManager-API
        - rmdir /s "C:\GitLab-Runner\builds\Sns1WAaE\0\RomanLeichnig\backend-bet-manager-group2"
    artifacts:
        paths:
            - 3wBetManager-API/
            - FetchFootballData/

#================================
# Deploy
#================================

deploy:
    stage: deploy
    only:
        - master
    script:
        - 'call deploy.bat'
    dependencies:
        - build